### ISSUE TITLE
Cannot retrieve pixel format info from device [Error While Encoding v4l2 command via ioctl]

### ISSUE THREAD

**Issue by tarunKoyalwar** [vladimirvivien/go4vl#7] opened 2021-10-23 20:29 UTC
## Error
`device.GetPixFormat()` always fails with error  `device: pix format failed: unsupported error`
if we do a system call trace i get following

~~~
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x56, 0x4, 0xcc), 0xc000076ca8) = -1 ENOTTY (Inappropriate ioctl for device)
write(1, "failed to get pix format\n", 25failed to get pix format
~~~

It looks like encoded command is not `VIDIOC_G_FMT` and is not recognized by kernel.

```
package main

import (
	"fmt"

	"github.com/vladimirvivien/go4vl/v4l2"
)

func main() {
	device, err := v4l2.Open("/dev/video0")
	if err != nil {
		panic(err)
	}

	_, err = device.GetPixFormat()
	if err != nil {
		fmt.Println("failed to get pix format")
		panic(err)
	}
}

```

My kernel is 
~~~
Linux endless 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux
~~~

## Cause
I don't think this problem is caused by kernel.
I can use <linux/videodev2.h> and it does not cause this error

With the C API I get
~~~
ioctl(3, VIDIOC_G_FMT, {type=V4L2_BUF_TYPE_VIDEO_CAPTURE, fmt.pix={width=1280, height=720, pixelformat=v4l2_fourcc('M', 'J', 'P', 'G') /* V4L2_PIX_FMT_MJPEG */, field=V4L2_FIELD_NONE, bytesperline=0, sizeimage=1843200, colorspace=V4L2_COLORSPACE_SRGB}}) = 0
~~~

It looks like the **problem is caused in ioctl encoding functions.** I rechecked the ioct.go but could not find the problem

**Comment by vladimirvivien** [comment] 2021-11-03 12:55
@EtienneBruines @tarunKoyalwar 
Apologies for late reply, I have been on vacation and got busy at work.

This is an awesome thread and appreciate all the great information/comments you both have provided.
But, I must start my reply with the following disclaimers:

* This is a highly early and alpha Go project with great aspiration, but it's not there yet.
* All code have been tested solely on Linux running on a Raspberry pi 3 with latest Kernel release
* I have been able to successfully create a webcam using the code, the Pi, and a webcam

So as you can see this is pretty early stuff. Having said all of that, I welcome your great feedback and will be investigating this issue this week. My lofty aspiration for this project is to provide a great idiomatic Go experience using the API without cgo. However, I havent used it in enough cases to know if that's a possibility. 

I will spend time on this issue to see if it's something that can be quickly resolved or need to completely change direction of the project (using cgo).

Thanks.

**Comment by tarunKoyalwar** [comment] 2021-11-04 18:28
@vladimirvivien @EtienneBruines  I believe following data would help.

~~~
package main

/*
#include <linux/videodev2.h>
#include <stdio.h>

struct v4l2_format fmt;

int mains(){
    printf("Size of v4l2_format(official) struct in c is %d\n",sizeof(fmt));
    return 0;
}
*/
import "C"
import (
	"fmt"
	"unsafe"
)

type v4l2Format struct {
	StreamType uint32
	fmt        [200]byte
}

func main() {
	// type C.v4l2_format
	var vformat v4l2Format
	C.mains()
	fmt.Printf("Size of v4l2_struct(official) in golang is %v\n", unsafe.Sizeof(C.fmt))
	fmt.Printf("Size of golang defined v4l2format struct in golang is %v\n", unsafe.Sizeof(vformat))
}
~~~
This program returns 
![Screenshot_10](https://user-images.githubusercontent.com/45962551/140397572-a55ae27c-c3ac-4a3b-b5f1-c6b4ccdaa168.png)


It looks like the v4l2format defined here(https://github.com/vladimirvivien/go4vl/blob/aab6d9c4a2496f2e9bc90c2763e94eba389bde9d/v4l2/format.go#L289) 

is short of 4 bytes . It looks like this missing 4 bytes are causing above discussed errors. It looks like a field (possibly  __u32 which is of size 4 bytes) is missing in golang implementation of v4l2_format

**Comment by EtienneBruines** [comment] 2021-11-05 07:27
@tarunKoyalwar that snippet is really helpful! (Especially with debugging)

From the looks of it (earlier on), those 4 bytes seem to be in between the `StreamType` and the `fmt [200]byte` - possibly to help define which of the `union` types it is.

**Comment by vladimirvivien** [comment] 2021-11-05 15:39
@tarunKoyalwar @EtienneBruines 
I really appreciate the code snippet for cgo. This weekend I will spend time figuring out which way I want to take the project (and how, if any, cgo can be used). 

As you have experienced, alignment is a class of bugs that keeps popping up and depends on the architecture/word size. For instance, because I test the code on a 32-bit RPi, I crafted the code to work on that platform. As you encountered, it's failing on others.  One idea running through my head is to use Go build tags to target particular platforms.

Overall, I really appreciate the feedback. I like that snippet above and will be valuable in testing along with dtrace.

**Comment by vladimirvivien** [comment] 2021-11-05 15:53
There is no missing struct member.  The problem is go compiler sometimes treats alignment differently depending on arc targeted. I ran into that issue (cant remember where) in other part of the code and it's tricky.  I will reboot the project this weekend to investigate how this can be fixed once and for all.

> is short of 4 bytes . It looks like this missing 4 bytes are causing above discussed errors. It looks like a field (possibly __u32 which is of size 4 bytes) is missing in golang implementation of v4l2_format

**Comment by tarunKoyalwar** [comment] 2021-11-05 17:04
> There is no missing struct member. The problem is go compiler sometimes treats alignment differently depending on arc targeted. I ran into that issue (cant remember where) in other part of the code and it's tricky. I will reboot the project this weekend to investigate how this can be fixed once and for all.
> 
> > is short of 4 bytes . It looks like this missing 4 bytes are causing above discussed errors. It looks like a field (possibly __u32 which is of size 4 bytes) is missing in golang implementation of v4l2_format

I think it would be great if we can add some unit testing to important parts of project like (ioctl commands , structs etc) , this would help the project to avoid future errors and keep up the standards with v4l2 api. Also the unit testing should use cgo , something similar to above program . I intend to use this project for my upcoming projects , let me know if I can help speed up any process

**Comment by vladimirvivien** [comment] 2021-11-05 21:02
@tarunKoyalwar Yeah, in the future, something to help unit test would be great.  In the initial part of the project I am trying to basically prove the concept is workable (which it is). Unit tests would require either

* a mock kernel function to handle the ioctl calls (that simulates connected devices, etc)
* run tests in linux container and test in it (using a mock virtual device if such things exists, i would image yes)
* Combination of two (not sure)

Definitely something to look into and some ggreat ideas

**Comment by vladimirvivien** [comment] 2021-11-09 01:37
@tarunKoyalwar @EtienneBruines 
Hello, I spent last weekend playing around an example that uses cgo.  See `examples/native_c_types`. Please run on the device that was failing due to alignment to see if that problem still persists with cgo.

**Comment by EtienneBruines** [comment] 2021-11-09 08:13
@vladimirvivien I played around with it a little bit, and it seems to have done wonders!

I was able to `setFormat` and then verify the settings using `getFormat` reliably now. :tada:

**Comment by vladimirvivien** [comment] 2021-11-09 11:15
@EtienneBruines Thanks for validating. To be clear, did you test the code in `example/native_c_types` or the regular v4l2 API? (I ask because I had some old uncommitted code changes that finally got pushed. I wanna make sure to understand which changes made a difference for you).

**Comment by EtienneBruines** [comment] 2021-11-09 11:21
I used the code at `native_c_types`, albeit with minor `BufTypeVideoOutput` because that's what I'm using v4l2 for. 

<details>
  <summary>Click to expand - Full code that I used</summary>

```go
package main

/*
#include <linux/videodev2.h>
*/
import "C"
import (
	"bytes"
	"fmt"
	"github.com/vladimirvivien/go4vl/v4l2"
	"image"
	"image/color"
	"image/draw"
	"image/jpeg"
	"log"
	"os"
	"time"
	"unsafe"

	sys "golang.org/x/sys/unix"
)

type FrameWriter func(draw.Image) bool

const (
	devName     = "/dev/video10"
	jpegQuality = 80
	width       = 640
	height      = 480
	fps         = 4
)

func StartWebcam(writer FrameWriter) error {
	// open device
	devFile, err := os.OpenFile(devName, sys.O_RDWR|sys.O_NONBLOCK, 0666)
	if err != nil {
		return fmt.Errorf("unable to open video device: %q: %w", devName, err)
	}
	defer devFile.Close()
	fd := devFile.Fd()

	// Set the format
	targetFmt := PixelFmtMJPEG
	if err := setFormat(fd, PixFormat{
		Width:       width,
		Height:      height,
		PixelFormat: targetFmt,
		Field:       FieldNone,
	}); err != nil {
		log.Fatal("setFormat", err)
	}

	pixFmt, err := getFormat(fd)
	if err != nil {
		log.Fatal("getFormat", err)
	}
	log.Printf("Format set: %dx%d pixel format %d [FmtMJPG]", pixFmt.Width, pixFmt.Height, pixFmt.PixelFormat)

	if pixFmt.PixelFormat != targetFmt {
		log.Fatalf("Unable to update PixFormat - got %d instead of %d\n", pixFmt, targetFmt)
	}

	frame := image.NewRGBA(image.Rect(0, 0, width, height))
	ticker := time.NewTicker(time.Second / fps)

	var buf bytes.Buffer
	for {
		select {
		case <-ticker.C:
			updated := writer(frame)
			if updated || buf.Len() == 0 {
				buf.Reset()
				err = jpeg.Encode(&buf, frame, &jpeg.Options{Quality: jpegQuality})
				if err != nil {
					return fmt.Errorf("unable to encode frame to JPEG: %w", err)
				}
			}

			_, err = sys.Write(int(fd), buf.Bytes())
			if err != nil {
				log.Println("unable to write frame:", err)
			}
			fmt.Print(".")
		}
	}
}

// ========================= Pixel Format =========================
// https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/videodev2.h#L682
var (
	PixelFmtMJPEG uint32 = C.V4L2_PIX_FMT_MJPEG
)

// buff stream types
// https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/videodev2.h#L142
const (
	BufTypeVideoOutput uint32 = C.V4L2_BUF_TYPE_VIDEO_OUTPUT
)

// Pix format field types
// https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/videodev2.h#L89
const (
	FieldNone uint32 = C.V4L2_FIELD_NONE
)

// setsFormat sets pixel format of device
func setFormat(fd uintptr, pixFmt PixFormat) error {
	var v4l2Fmt C.struct_v4l2_format
	v4l2Fmt._type = C.uint(BufTypeVideoOutput)
	*(*C.struct_v4l2_pix_format)(unsafe.Pointer(&v4l2Fmt.fmt[0])) = *(*C.struct_v4l2_pix_format)(unsafe.Pointer(&pixFmt))

	if err := v4l2.Send(fd, C.VIDIOC_S_FMT, uintptr(unsafe.Pointer(&v4l2Fmt))); err != nil {
		return err
	}
	log.Printf("setting format to: %dx%d\n", pixFmt.Width, pixFmt.Height)
	return nil
}

func getFormat(fd uintptr) (PixFormat, error) {
	var v4l2Fmt C.struct_v4l2_format
	v4l2Fmt._type = C.uint(BufTypeVideoOutput)

	if err := v4l2.Send(fd, C.VIDIOC_G_FMT, uintptr(unsafe.Pointer(&v4l2Fmt))); err != nil {
		return PixFormat{}, err
	}

	var pixFmt PixFormat
	*(*C.struct_v4l2_pix_format)(unsafe.Pointer(&pixFmt)) = *(*C.struct_v4l2_pix_format)(unsafe.Pointer(&v4l2Fmt.fmt[0]))

	return pixFmt, nil

}

// PixFormat represents v4l2_pix_format
// https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/videodev2.h#L496
type PixFormat struct {
	Width        uint32
	Height       uint32
	PixelFormat  uint32
	Field        uint32
	BytesPerLine uint32
	SizeImage    uint32
	Colorspace   uint32
	Priv         uint32
	Flags        uint32
	YcbcrEnc     uint32
	Quantization uint32
	XferFunc     uint32
}

func main () {
	writer := func(frame draw.Image) bool {
		draw.Draw(frame, frame.Bounds(), image.NewUniform(color.RGBA{255, 0, 0, 255}), image.Point{}, draw.Src)
		return true // false to cache the previous frame
	}
	
	StartWebcam(writer)
}
```
</details>

**Comment by vladimirvivien** [comment] 2021-11-09 12:56
@EtienneBruines that is great!!!!
This confirms that cgo works (better than crafting Go types manually for C counter parts). So this means I will do a refactor of current code to integrate cgo-generated types.

Again, thank you considering using this code.

**Comment by vladimirvivien** [comment] 2021-11-13 19:14
@EtienneBruines and @tarunKoyalwar 
Based on this thread, I have gone ahead and refactored the source code to use cgo-generated Go types (instead of hand-crafted ones) to automatically handle type alignment issues. 

> See https://github.com/vladimirvivien/go4vl/tree/cgo-refactor

The new requirements are:
* Build on linux with videodev2.h header file
* Build environment with `include` path setup

Please give it a try, let me know if your issues go away after a recompile.

**Closed** 2022-01-11 14:44 UTC
